# Generated by Django 6.0.4 on 2026-04-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_ejemplares',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(default='disponible', max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='librosApp.libro')),
            ],
        ),
    ]
