# Generated by Django 6.0.4 on 2026-04-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0003_ejemplar_fecha_llegada_alter_ejemplar_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
