# Generated by Django 6.0.4 on 2026-04-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librosApp', '0005_remove_libro_cantidad_ejemplares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.AddField(
            model_name='libro',
            name='codigo_libro',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
