# Generated by Django 6.0.4 on 2026-04-10 16:51

import datetime
import django.db.models.deletion
import prestamoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('librosApp', '0005_remove_libro_cantidad_ejemplares'),
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=datetime.date.today)),
                ('fecha_devolucion', models.DateField(default=prestamoApp.models.fecha_devolucion_default)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('P', 'Prestado'), ('D', 'Disponible'), ('A', 'Atrasado')], max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='librosApp.ejemplar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarioApp.usuario')),
            ],
        ),
    ]
