# Generated by Django 6.0.4 on 2026-04-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('P', 'Prestado'), ('D', 'Disponible'), ('A', 'Atrasado')], default='P', max_length=1),
        ),
    ]
