# Generated by Django 6.0.4 on 2026-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0003_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
