# Generated by Django 4.2.23 on 2026-04-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0004_usuario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargadobiblioteca',
            name='nivel',
            field=models.CharField(choices=[('BASICA', 'Basica'), ('MEDIA', 'Media')], default='BASICA', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='encargado_agrego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_agregados', to='usuarioApp.encargadobiblioteca'),
        ),
    ]
